datadir: "./dataset/EUR-Lex/"
text2text:
  istrain: True
  model_name: "pegasus"
  batch_size: 2
  outputmodel: "pegasus_save"
  checkdir: "pegasus_check"
  s_pre_trn: True
  is_pre_tst: True
  data_size: 16
combine:
  is_combine: True
  combine_model: 'bi-encoder'
rank:
  is_rank_train: True
  batch_size: 16
  rank_model: 'all-MiniLM-L6-v2'
  is_ranking: True
  data_size: 128
  rankmodel_save: "bi_en"
